version: '3'

services:
  2dns:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${PORT:-53}:${PORT:-53}/udp"
      - "${PORT:-53}:${PORT:-53}/tcp"
    volumes:
      - ./records:/data
    environment:
      - PORT=${PORT:-53}
      - MODE=${MODE:-production}
      - CSV_PATH=/data/records.csv
      - TTL=${TTL:-60}
      - VERBOSE=${VERBOSE:-false}
    restart: unless-stopped
    container_name: 2dns
