version: '3'

services:
  2dns:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    restart: unless-stopped
    container_name: 2dns
