name: Dependency Check

on:
  push:
    branches: [ main, master ]
    paths:
      - 'web/package.json'
      - 'web/pnpm-lock.yaml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'web/package.json'
      - 'web/pnpm-lock.yaml'
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.2.0
          
      - name: Install dependencies
        run: |
          cd web
          pnpm install --frozen-lockfile
          
      - name: Run security audit
        run: |
          cd web
          pnpm audit
        continue-on-error: true
        
      - name: Check for outdated packages
        run: |
          cd web
          pnpm outdated
        continue-on-error: true
        
      - name: Check for extraneous packages
        run: |
          cd web
          pnpm ls --depth=0
        continue-on-error: true
        
  node-version:
    name: Node.js Version Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Check Node.js version in package.json
        run: |
          cd web
          if [ -f package.json ]; then
            NODE_VERSION=$(grep -o '"node": "[^"]*"' package.json | cut -d'"' -f4 | tr -d '^>=~')
            echo "Required Node.js version: $NODE_VERSION"
            
            if [ -z "$NODE_VERSION" ]; then
              echo "::warning::No Node.js version specified in package.json"
            fi
          else
            echo "::warning::package.json not found"
          fi
          
      - name: Check .nvmrc file
        run: |
          cd web
          if [ -f .nvmrc ]; then
            echo "Node.js version in .nvmrc: $(cat .nvmrc)"
          else
            echo "::warning::.nvmrc file not found"
          fi
