name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["Go Tests"]
    types:
      - completed
    branches: [ main ]
  push:
    branches: [ main ]
    tags: [ 'v*' ]
    paths:
      - 'docker/**'
      - '.github/workflows/docker-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'docker/**'
      - '.github/workflows/docker-build.yml'
  workflow_dispatch:

jobs:
  build:
    # 只有当触发工作流的工作流运行成功时才运行
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # 生成日期时间标签
      - name: Generate date-time tag
        id: datetime
        run: echo "datetime=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/2dns
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=${{ steps.datetime.outputs.datetime }}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
