import '@testing-library/jest-dom'

// Mock Prism.js globally
global.Prism = {
  highlight: jest.fn((code, language) => code),
  languages: {
    javascript: {},
    typescript: {},
    python: {},
    go: {},
    java: {},
    json: {},
    bash: {},
    shell: {},
  },
  highlightAll: jest.fn(),
  highlightElement: jest.fn(),
}

// Mock Lucide React icons
jest.mock('lucide-react', () => {
  const MockedIcon = ({ children, ...props }) => <span {...props}>{children}</span>
  
  return {
    Check: MockedIcon,
    Copy: MockedIcon,
    Terminal: MockedIcon,
    Info: MockedIcon,
    AlertCircle: MockedIcon,
    Play: MockedIcon,
    Loader2: MockedIcon,
    Zap: MockedIcon,
    Globe: MockedIcon,
    Network: MockedIcon,
    Search: MockedIcon,
    Code: MockedIcon,
    Server: MockedIcon,
    Shield: MockedIcon,
    Wifi: MockedIcon,
    Monitor: MockedIcon,
    Database: MockedIcon,
    Cloud: MockedIcon,
    Settings: MockedIcon,
    ExternalLink: MockedIcon,
    ChevronDown: MockedIcon,
    ChevronUp: MockedIcon,
    ChevronRight: MockedIcon,
    ChevronLeft: MockedIcon,
    Eye: MockedIcon,
    EyeOff: MockedIcon,
    Activity: MockedIcon,
    BarChart: MockedIcon,
    TrendingUp: MockedIcon,
    Users: MockedIcon,
    Mail: MockedIcon,
    Phone: MockedIcon,
    MapPin: MockedIcon,
    Calendar: MockedIcon,
    Clock: MockedIcon,
    Download: MockedIcon,
    Upload: MockedIcon,
    FileText: MockedIcon,
    Image: MockedIcon,
    Video: MockedIcon,
    Music: MockedIcon,
    Archive: MockedIcon,
    Trash2: MockedIcon,
    Edit: MockedIcon,
    Plus: MockedIcon,
    Minus: MockedIcon,
    X: MockedIcon,
    Menu: MockedIcon,
    Home: MockedIcon,
    User: MockedIcon,
    Lock: MockedIcon,
    Unlock: MockedIcon,
    Star: MockedIcon,
    Heart: MockedIcon,
    MessageCircle: MockedIcon,
    Share: MockedIcon,
    Bookmark: MockedIcon,
    Flag: MockedIcon,
    Bell: MockedIcon,
    AlertTriangle: MockedIcon,
    HelpCircle: MockedIcon,
    MoreHorizontal: MockedIcon,
    MoreVertical: MockedIcon,
    Filter: MockedIcon,
    Sort: MockedIcon,
    Refresh: MockedIcon,
    RotateCcw: MockedIcon,
    Save: MockedIcon,
    Send: MockedIcon,
    Printer: MockedIcon,
    Scissors: MockedIcon,
    PaperClip: MockedIcon,
    Link: MockedIcon,
    LinkOff: MockedIcon,
    Maximize: MockedIcon,
    Minimize: MockedIcon,
    ZoomIn: MockedIcon,
    ZoomOut: MockedIcon,
    Volume2: MockedIcon,
    VolumeX: MockedIcon,
    Pause: MockedIcon,
    StopCircle: MockedIcon,
    SkipBack: MockedIcon,
    SkipForward: MockedIcon,
    FastForward: MockedIcon,
    Rewind: MockedIcon,
    Repeat: MockedIcon,
    Shuffle: MockedIcon,
    Mic: MockedIcon,
    MicOff: MockedIcon,
    Camera: MockedIcon,
    CameraOff: MockedIcon,
    Grid: MockedIcon,
    List: MockedIcon,
    Layers: MockedIcon,
    Package: MockedIcon,
    Box: MockedIcon,
    Truck: MockedIcon,
    Map: MockedIcon,
    Navigation: MockedIcon,
    Compass: MockedIcon,
    Target: MockedIcon,
    Award: MockedIcon,
    Trophy: MockedIcon,
    Gift: MockedIcon,
    ShoppingCart: MockedIcon,
    CreditCard: MockedIcon,
    DollarSign: MockedIcon,
    BarChart2: MockedIcon,
    PieChart: MockedIcon,
    LineChart: MockedIcon,
    Briefcase: MockedIcon,
    Building: MockedIcon,
    Factory: MockedIcon,
    Truck: MockedIcon,
    Plane: MockedIcon,
    Car: MockedIcon,
    Bike: MockedIcon,
    Bus: MockedIcon,
    Train: MockedIcon,
    Ship: MockedIcon,
    Anchor: MockedIcon,
    Umbrella: MockedIcon,
    Sun: MockedIcon,
    Moon: MockedIcon,
    CloudRain: MockedIcon,
    CloudSnow: MockedIcon,
    CloudLightning: MockedIcon,
    Wind: MockedIcon,
    Thermometer: MockedIcon,
    Droplet: MockedIcon,
    Flame: MockedIcon,
    Zap: MockedIcon,
    Battery: MockedIcon,
    BatteryLow: MockedIcon,
    Cpu: MockedIcon,
    HardDrive: MockedIcon,
    Smartphone: MockedIcon,
    Tablet: MockedIcon,
    Laptop: MockedIcon,
    Desktop: MockedIcon,
    Watch: MockedIcon,
    Headphones: MockedIcon,
    Speaker: MockedIcon,
    Radio: MockedIcon,
    Tv: MockedIcon,
    GameController: MockedIcon,
    Gamepad2: MockedIcon,
    Joystick: MockedIcon,
    MousePointer: MockedIcon,
    Keyboard: MockedIcon,
    Type: MockedIcon,
    AlignLeft: MockedIcon,
    AlignCenter: MockedIcon,
    AlignRight: MockedIcon,
    AlignJustify: MockedIcon,
    Bold: MockedIcon,
    Italic: MockedIcon,
    Underline: MockedIcon,
    Strikethrough: MockedIcon,
    Highlighter: MockedIcon,
    PaintBucket: MockedIcon,
    Palette: MockedIcon,
    Eyedropper: MockedIcon,
    Pipette: MockedIcon,
    Brush: MockedIcon,
    Pen: MockedIcon,
    PenTool: MockedIcon,
    Eraser: MockedIcon,
    Ruler: MockedIcon,
    Move: MockedIcon,
    RotateCw: MockedIcon,
    Scale: MockedIcon,
    FlipHorizontal: MockedIcon,
    FlipVertical: MockedIcon,
    Crop: MockedIcon,
    Square: MockedIcon,
    Circle: MockedIcon,
    Triangle: MockedIcon,
    Hexagon: MockedIcon,
    Octagon: MockedIcon,
    Pentagon: MockedIcon,
    Diamond: MockedIcon,
    Polygon: MockedIcon,
    Spline: MockedIcon,
    Bezier: MockedIcon,
    Vector: MockedIcon,
    Anchor: MockedIcon,
    Crosshair: MockedIcon,
    Focus: MockedIcon,
    ScanLine: MockedIcon,
    QrCode: MockedIcon,
    Barcode: MockedIcon,
    Hash: MockedIcon,
    AtSign: MockedIcon,
    Percent: MockedIcon,
    Ampersand: MockedIcon,
    Quote: MockedIcon,
    Asterisk: MockedIcon,
    Equal: MockedIcon,
    NotEqual: MockedIcon,
    GreaterThan: MockedIcon,
    LessThan: MockedIcon,
    GreaterThanEqual: MockedIcon,
    LessThanEqual: MockedIcon,
    PlusCircle: MockedIcon,
    MinusCircle: MockedIcon,
    XCircle: MockedIcon,
    CheckCircle: MockedIcon,
    CheckCircle2: MockedIcon,
    AlertCircle: MockedIcon,
    HelpCircle: MockedIcon,
    InfoCircle: MockedIcon,
    XOctagon: MockedIcon,
    AlertOctagon: MockedIcon,
    StopCircle: MockedIcon,
    PlayCircle: MockedIcon,
    PauseCircle: MockedIcon,
    Disc: MockedIcon,
    Disc2: MockedIcon,
    Disc3: MockedIcon,
    Circle: MockedIcon,
    CircleDot: MockedIcon,
    DotSquare: MockedIcon,
    Square: MockedIcon,
    RectangleHorizontal: MockedIcon,
    RectangleVertical: MockedIcon,
    RoundedRect: MockedIcon,
    Squircle: MockedIcon,
  }
})

// Mock Next.js router
jest.mock('next/router', () => ({
  useRouter: () => ({
    push: jest.fn(),
    pathname: '/',
    query: {},
  }),
}))

// Mock next/navigation
jest.mock('next/navigation', () => ({
  useRouter: () => ({
    push: jest.fn(),
    replace: jest.fn(),
    back: jest.fn(),
    forward: jest.fn(),
    refresh: jest.fn(),
    prefetch: jest.fn(),
  }),
  usePathname: () => '/',
  useSearchParams: () => new URLSearchParams(),
}))

// Mock IntersectionObserver
global.IntersectionObserver = class IntersectionObserver {
  constructor() {}
  observe() {}
  disconnect() {}
  unobserve() {}
}

// Mock ResizeObserver
global.ResizeObserver = class ResizeObserver {
  constructor() {}
  observe() {}
  disconnect() {}
  unobserve() {}
}

// Mock clipboard API
Object.assign(navigator, {
  clipboard: {
    writeText: jest.fn(() => Promise.resolve()),
    readText: jest.fn(() => Promise.resolve('')),
  },
})

// Mock window.matchMedia
Object.defineProperty(window, 'matchMedia', {
  writable: true,
  value: jest.fn().mockImplementation(query => ({
    matches: false,
    media: query,
    onchange: null,
    addListener: jest.fn(), // deprecated
    removeListener: jest.fn(), // deprecated
    addEventListener: jest.fn(),
    removeEventListener: jest.fn(),
    dispatchEvent: jest.fn(),
  })),
}) 